### ISSUE TITLE
Missing image of TROG task

### ISSUE THREAD

**Issue by ShawnKing98** [alvinwmtan/dev-bench#2]
Hi, it seems that image 67&68 for TROG task are missing in the original [LEVANTE repo](https://github.com/levante-framework/core-tasks/tree/main/assets/TROG/original) while the corresponding metadata still occurs in the csv file, causing a bug while running evaluation. Did you just ignore those testing samples in your paper, or you have the missing samples but are not able to release them?

**Comment by alvinwmtan** [comment]
Apologies, I'm not sure why they're missing on the LEVANTE repo. They're present in another folder in that repo (confusingly); I have just added them to the present one to avoid confusion. Thanks for the heads-up!
